import type { Metadata } from "next";
import "./globals.css";
import { Lato, Grenze_Gotisch } from 'next/font/google'
import localFont from 'next/font/local'

const against = localFont({
  src: '/Fonts/against regular.ttf',
  variable: '--font-against',
  weight: '400',
  style: 'normal',
})

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '100', '300', '700'],
  variable: '--font-lato',
})

const grenze = Grenze_Gotisch({
  subsets: ['latin'],
  weight: ['400', '100', '700'],
  variable: '--font-grenze',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} ${grenze.variable} ${against.variable} bg-[#090909]`}>
        {children}
      </body>
    </html>
  );
}
